### ISSUE TITLE
How to configure path aliases to work with your configuration

### ISSUE THREAD

**Issue by 7iomka** [leoroese/turborepo-tutorial#1]
Hi!
First of all - thank you very much for awesome video tutorial.
Now I have very hot bug with current configuration - it not possible to use paths aliases inside apps.

In my apps I use very common approach:
```json
  "compilerOptions": {
    "noEmit": true,
    "baseUrl": ".",
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
  },
```
And I prefer to have ALL files inside `src` folder (includes styles), so, i moved `styles` folder to src.
Then, conform my app tsconfig, in `_app.tsx` I replace relative styles import to aliased one:
```tsx
import '../../styles/globals.css'
```
to
```tsx
import '@/styles/globals.css'
```
Then, I restarted server (required for next.js recognize aliased imports) - styles imports works fine, but I get eslint errors
1) In each app file:
```tsx
Resolve error: ENOENT: no such file or directory, stat 'tsconfig.json'
```

2) In import rule:
```tsx
Unable to resolve path to module '@/styles/globals.css'. eslintimport/no-unresolved
```

Please, help me, how to fix this errors?
Seems after `paths` change `project` field get resolved at the root level (not at the app level).
Another question - what is `'package/tsconfig.json'` path meen? I googled about that case of path inside `project` but not found anything.

```js
'import/resolver': {
      node: {
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
        project: ['tsconfig.json', 'package/tsconfig.json'],
      },
      typescript: {
        alwaysTryTypes: true,
        project: ['tsconfig.json', 'package/tsconfig.json'],
      },
    },
```

Thanks for all!

**Comment by 7iomka** [comment]
I thinks `paths` conflicts with
```js
  parserOptions: {
    root: true,
    tsconfigRootDir: __dirname,
     project: ['./tsconfig.json'],
   },
```

Need workaround

**Comment by 7iomka** [comment]
If I remove `project` field, local eslint errors not shown, but if I have in vscode settings 
`"eslint.validate": ["vue", "html", "javascript", "typescript", "javascriptreact", "typescriptreact"],` this make error in vscode alert 
`Error while loading rule '@typescript-eslint/dot-notation': You have used a rule which requires parserServices to be generated.`

**Comment by leoroese** [comment]
Hey 7iomka, Yes I recently discovered this strange issue as well when doing part2 of my tutorial. When adding path aliases eslint was disabled, but when fixing eslint than unable to import the module. I am going to try and see if I can figure out why this is happening!

**Comment by leoroese** [comment]
Hey @7iomka I just pushed up a new change to the main branch that has absolute imports working along with lining. Let me know if you have any questions!

**Comment by leoroese** [comment]
Okay I think I was able to fix it. Just pushed up changes to the main branch. Check out eslint-next.js, root level jest.config.js, next-app/jest.config.js, and next-app/tsconfig.json, next-app/.eslintrc.js.

It seems to be linting and also allowing for absolute imports.
